### ISSUE TITLE
Allow skipping over files without front matter

### ISSUE THREAD

**Issue by soumak77** [base-apps/base-apps-router#2]
While trying to update to v1.2, I noticed that the router now produces output for all files passed through the router instead of just files that contain front matter.  When this happens and you load up the app, you get the following generic error reported by angular:

```
Error: State must have a valid name
```

An option should be added to the router to ignore files without front matter or possible just make that the default behavior since I'm not sure there is a use case where you would want to produce router configurations for files without front matter.

**Comment by soumak77** [comment]
@gakimball is this just a bug or should the option be added to run in both modes?

**Comment by gakimball** [comment]
That sounds like a bug. `addRoute()` should not be called if a page has no Front Matter.
